### ISSUE TITLE
New standard published!

### ISSUE THREAD

**Issue by elstanto** [pinski1/PQ60-Template#1]
Hi,

They've actually published V1 of the standard now - www.pq.info. Unfortunately they have completely changed the bus pinout.

Not sure if I agree with the changes. I need to find out exactly what they are doing with the power busses - namely where does 'system ground' orginate?

I'm releasing an updated version on SurreyEARS' repo with some hopefully clever vias that allow you to easily support the bus dropping protocol.

**Comment by pinski1** [comment]
I've gone an updated the EPS without updating my template, I'll try and get on that soonest.

**Comment by pinski1** [comment]
Latest commit (5a41f6b0a95ee131a6716c3c6b18630d20884289) fixes this problem.
